import React from "react";
import {Pressable,ScrollView,StyleProp,StyleSheet,Text,TextInput,TextInputProps,View,ViewStyle} from "react-native";
export const C={forest:"#173d2a",forest2:"#2c6b4a",gold:"#c4a35a",paper:"#fbf8f1",canvas:"#f2eee5",ink:"#1d2a22",muted:"#657067",line:"#d9d3c7",white:"#fff",critical:"#9d2f2f",high:"#c77b22",moderate:"#8b7a2a",low:"#4b7b58"};
export function Screen({children,scroll=true,style}:{children:React.ReactNode;scroll?:boolean;style?:StyleProp<ViewStyle>}){const content=<View style={[styles.screen,style]}>{children}</View>; return scroll?<ScrollView contentContainerStyle={styles.scroll}>{content}</ScrollView>:content}
export function Card({children,style}:{children:React.ReactNode;style?:StyleProp<ViewStyle>}){return <View style={[styles.card,style]}>{children}</View>}
export function Title({children,small=false}:{children:React.ReactNode;small?:boolean}){return <Text style={small?styles.h2:styles.h1}>{children}</Text>}
export function Label({children}:{children:React.ReactNode}){return <Text style={styles.label}>{children}</Text>}
export function Input(p:TextInputProps){return <TextInput placeholderTextColor="#89918b" {...p} style={[styles.input,p.style]}/> }
export function Button({children,onPress,secondary=false,disabled=false}:{children:React.ReactNode;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[styles.btn,secondary&&styles.btn2,disabled&&{opacity:.45}]}><Text style={[styles.btnText,secondary&&styles.btnText2]}>{children}</Text></Pressable>}
export function Badge({children,level}:{children:React.ReactNode;level?:string}){let bg=C.low;if(level==="CRITICAL")bg=C.critical;else if(level==="HIGH")bg=C.high;else if(level==="MODERATE")bg=C.moderate;return <View style={[styles.badge,{backgroundColor:bg}]}><Text style={styles.badgeText}>{children}</Text></View>}
export function Row({children}:{children:React.ReactNode}){return <View style={styles.row}>{children}</View>}
export const styles=StyleSheet.create({screen:{padding:18,backgroundColor:C.canvas,flex:1},scroll:{paddingBottom:40},h1:{fontSize:28,fontWeight:"800",color:C.ink,marginBottom:6},h2:{fontSize:19,fontWeight:"800",color:C.ink,marginBottom:8},label:{fontSize:12,fontWeight:"700",color:C.muted,marginTop:12,marginBottom:6,textTransform:"uppercase",letterSpacing:.5},input:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:10,paddingHorizontal:12,paddingVertical:11,color:C.ink,fontSize:15},card:{backgroundColor:C.paper,borderRadius:14,padding:15,borderWidth:1,borderColor:C.line,marginTop:12},btn:{backgroundColor:C.forest,borderRadius:10,paddingVertical:13,paddingHorizontal:16,alignItems:"center",marginTop:12},btn2:{backgroundColor:C.white,borderWidth:1,borderColor:C.forest},btnText:{color:C.white,fontWeight:"800",fontSize:14},btnText2:{color:C.forest},badge:{alignSelf:"flex-start",borderRadius:20,paddingHorizontal:9,paddingVertical:4},badgeText:{color:C.white,fontSize:10,fontWeight:"800"},row:{flexDirection:"row",gap:10,alignItems:"center"}});